# Site settings
title: Second Star Labs
email: rocketeer.captproton@gmail.com
description: "Second Star Labs successfully provides Agile Ruby on Rails (RoR) Development and Consulting."
baseurl: ""
url: "http://www.SecondStarLabs.com"
twitter_username: captproton
github_username:  captproton

# Build settings
markdown: redcarpet
permalink: pretty
